const PERMISSIONS = [
	// Users
	"CREATE_THREADS",
	"DELETE_THREADS",
	"CREATE_COMMENTS",
	"DELETE_COMMENTS",
	"CAST_VOTES",

	// Moderators
	"DELETE_OTHER_THREADS",
	"DELETE_OTHER_COMMENTS",
	"LOCK_THREADS",
	"PIN_THREADS",

	// Administrators
	"CREATE_FORUMS",
	"DELETE_FORUMS",
]
